Charity/Controllers/ACNCController.cs
using BuisnessEntities.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BuisnessEntities.Concrete;
using DCCA.Controllers;

namespace Charity.Controllers
{
    public class ACNCController : BaseController
    {
       
        public ACNCController() : base()
        {
            
        }
        // GET: ACNC
        public ActionResult GetACNCDetails(FilterCriteriaModel criteria)
        {
            var result = new ACNCRepository().GetListOfACNCDetails(criteria);
            string view = RenderRazorViewToString("_LoadResults", result.DataList);
            result.Data = view;
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetCareFor()
        {
            var result = new ACNCRepository().GetCareFor().ToList();
            string view = RenderRazorViewToString("_CareFor", result);
            return Json(new ActionOutput<string>{
                Object = view,
                Status = BuisnessEntities.Entities.ActionStatus.Successfull
            }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetHelpFor(int CareForId)
        {
            var result = new ACNCRepository().GetHelpFor(CareForId);
            string view = RenderRazorViewToString("_HelpForData", result);
            return Json(new ActionOutput<string>
            {
                Object = view,
                Status = BuisnessEntities.Entities.ActionStatus.Successfull
            }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetFacilities(int HelpForId)
        {
            var result = new ACNCRepository().GetFacility(HelpForId);
            string view = RenderRazorViewToString("_Facilities", result);
            return Json(new ActionOutput<string>
            {
                Object = view,
                Status = BuisnessEntities.Entities.ActionStatus.Successfull
            }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Volunteer()
        {
            try
            {
                string CountOldPeopleList = string.Empty;
                string InYearList = string.Empty;

                new ACNCRepository().GetListOfOldPeople(out  CountOldPeopleList, out InYearList);
                ViewBag.PeopleCount_List = CountOldPeopleList.Trim();
                ViewBag.Year_List = InYearList.Trim();

                return View();
            }
            catch (Exception)
            {
                throw;
            }
        }

        public ActionResult SearchForACNCDetails(FilterCriteriaModel filter)
        {
            var result = new ACNCRepository().SearchACNCDetails(filter);
            string view = RenderRazorViewToString("_LoadResults", result.DataList);
            result.Data = view;
            return Json(result, JsonRequestBehavior.AllowGet);
        }

    }
}

Charity/Controllers/DonationController.cs
using BuisnessEntities.Concrete;
using BuisnessEntities.Entities;
using BuisnessEntities.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Charity.Controllers
{
    public class DonationController : BaseController
    {
        public DonationController() : base()
        {

        }
        // GET: Donation
        public ActionResult Donate()
        {
            FilterCriteriaModel searchModel = new FilterCriteriaModel();
            searchModel.PageSize = 10;
            ListModel<ACNCModel> model = new ListModel<ACNCModel>();
            model.PagingResult = new ACNCRepository().GetListOfACNCDetails(searchModel);
            model.FilterCriteriaModel = searchModel;
            return View(model);
        }
    }
}

Charity/Views/Shared/_CareFor.cshtml
@model List<SelectListItem>
@Html.DropDownList("CareForSelect", Model.ToList(), new { @onchange = "GetHelpFor()" })

Charity/Views/Shared/_Facilities.cshtml
@model List<SelectListItem>
@Html.DropDownList("FacilitiesForSelect", Model.ToList())

Charity/Views/Shared/_HelpForData.cshtml
@model List<SelectListItem>
@Html.DropDownList("HelpForSelect", Model.ToList(),new { @onchange = "GetFaciltities()" })

Charity/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    
    <title>Real Heroes</title>
    <link href="~/Content/header.css" rel="stylesheet" />
    <link href="~/Content/Styles.css" rel="stylesheet" />
    <link href="~/Content/select2.min.css" rel="stylesheet" />
    <link href="/Content/paging.css" rel="stylesheet" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/sliderengine/amazingslider-1.css" rel="stylesheet" />
</head>
<body>
    <div class="headerwrapper">
        <div class="logoheader">
            <a href="@Url.Action("Index","Home")">
                <div id="headerimg"><img src="~/Images/CharityLogo.jpg" class="logo" /></div>
            </a>
            <div class="headertext"><a href="/index.php">RealHeroes</a></div>
            <div class="topheadermenu">
                <div class="topmenumobile hmenu"><a href="javascript:void(0);" onclick="mobileMenu()">≡ Menu</a></div>
                <div class="topmenubutton hmenu"><a href="@Url.Action("Donate","Donation")">Donate</a></div>
                <div class="topmenubutton hmenu"><a href="@Url.Action("Volunteer","ACNC")">Volunteer</a></div>
            </div>
        </div>

        <div class="clear"></div>
    </div>

    <div class="clear"></div>
    <div class="container body-content">
        @RenderBody()
    </div>
    <div class="footer">
        <div class="footermenu">

        </div>
        <p id="attribution">Our special thanks to ACNC for providning data under licence of Creative Commons Attribution 3.0 Australia.</p>
        <p>© RealHeroes Incorporated 2018</p>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/selectjs")
    @Scripts.Render("~/bundles/modernizr")

    <script src="~/Scripts/jquery.form.js"></script>
    <script src="/Scripts/UserDefinedScripts/Common.js"></script>
    <script src="/Scripts/UserDefinedScripts/paging.js"></script>
    @*<script src="~/Scripts/sliderengine/jquery.js"></script>*@
    <script src="~/Scripts/sliderengine/amazingslider.js"></script>
    <script src="~/Scripts/sliderengine/initslider-1.js"></script>
    
    
    @RenderSection("scripts", required: false)

</body>
</html>

Charity/Views/Shared/_LoadResults.cshtml
@using BuisnessEntities.Entities
@model List<ACNCModel>

    <table class="charitytable">
        <thead>
            <tr>
                <th id="Name">Charity Name</th>
                <th class="revenue tooltipd" id="Address">Address</th>
                <th class="staff tooltipd" id="Suburb">Town City</th>
                <th class="transparency tooltipd" id="CharitySize">Charity Size</th>
                <th class="finances tooltipd" id="Donate">Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr class="datarow" id="asthma-foundation-of-act-inc-">
                    <td>@item.CharityName</td>
                    <td>@item.Address</td>
                    <td>@item.Town</td>
                    <td>@item.Size</td>
                    <td>
                        @if (item.charityWebsite != null)
                        {
                            <a href="@item.charityWebsite"><i class="fa fa-usd-square"></i>Donate</a>
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table><br style="clear:both;">
    

Charity/Views/Shared/_Paging.cshtml
<div class="pagingWrapper">
    <div class="total-results">Total <span class="total-results-count"></span> Results</div>
    <div class="pager">
        <span class="first">« First</span> <span class="previous">Previous</span> <span class="numeric">
        </span><span class="next">Next</span> <span class="last">Last »</span>
    </div>
    <div class="pageInfo">
    </div>
</div>